org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true
kotlin.code.style=official
android.useAndroidX=true
kotlin.native.ignoreDisabledTargets=true

GROUP=tech.kloos.kompound
VERSION_NAME=0.1.0-SNAPSHOT
kompound.wasm=true

# Publishing metadata (used by convention plugin kompound.publishing)
POM_URL=https://github.com/KloosTech/Kompound
POM_SCM_URL=https://github.com/KloosTech/Kompound
POM_SCM_CONNECTION=scm:git:git://github.com/KloosTech/Kompound.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/KloosTech/Kompound.git
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=kloostech
POM_DEVELOPER_NAME=Kloos Tech
POM_DEVELOPER_URL=https://kloos.tech
