package tech.kloos.kompound.graph.model

import kotlin.jvm.JvmInline

/** Stable identity of a node. Supplied by you (or generated by the editor); persist it with the graph. */
@JvmInline
public value class NodeId(public val value: String) {
    override fun toString(): String = value
}

/** Identity of a port, unique inside its node. */
@JvmInline
public value class PortId(public val value: String) {
    override fun toString(): String = value
}

/** Identity of an edge. */
@JvmInline
public value class EdgeId(public val value: String) {
    override fun toString(): String = value
}

/** A specific port of a specific node. */
public data class PortRef(public val node: NodeId, public val port: PortId) {
    override fun toString(): String = "$node.$port"
}

/** Identity of a group of nodes. */
@JvmInline
public value class GroupId(public val value: String) {
    override fun toString(): String = value
}
