package tech.kloos.kompound.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.artifacts.ProjectDependency
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.create
import org.gradle.kotlin.dsl.dependencies
import org.gradle.kotlin.dsl.getByType
import org.gradle.kotlin.dsl.register
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension

public abstract class KompoundCatalogExtension {
    /** Fully qualified registry objects from external (Maven) modules. */
    public abstract val externalRegistries: ListProperty<String>
    public abstract val demoApi: Property<Any>
    public fun externalRegistry(fqn: String) { externalRegistries.add(fqn) }
}

/**
 * Applied to the catalog's shared KMP module. Generates `tech.kloos.kompound.catalog.KompoundAllDemos`
 * from the catalog's project dependencies that apply `tech.kloos.kompound.demos` (ADR 0003).
 */
public class KompoundCatalogPlugin : Plugin<Project> {
    override fun apply(project: Project): Unit = with(project) {
        val ext = extensions.create<KompoundCatalogExtension>("kompoundCatalog").apply {
            demoApi.convention("tech.kloos.kompound:kompound-demo:${KompoundCatalogPlugin::class.java.`package`.implementationVersion ?: "0.1.0-SNAPSHOT"}")
        }
        val outDir = layout.buildDirectory.dir("generated/kompound/commonMain/kotlin")
        val task = tasks.register<GenerateAllDemosTask>("generateKompoundAllDemos") {
            outputDirectory.set(outDir)
            externalRegistries.set(ext.externalRegistries)
        }

        pluginManager.withPlugin("org.jetbrains.kotlin.multiplatform") {
            val kmp = extensions.getByType<KotlinMultiplatformExtension>()
            kmp.sourceSets.getByName("commonMain") { kotlin.srcDir(task.flatMap { it.outputDirectory }) }
            afterEvaluate { kmp.sourceSets.getByName("commonMain").dependencies { api(ext.demoApi.get()) } }
            tasks.configureEach {
                if (name.startsWith("compileKotlin") || name.startsWith("compile") && name.endsWith("KotlinAndroid") ||
                    name == "compileAndroidMain" || name.startsWith("ksp")
                ) dependsOn(task)
            }
        }

        afterEvaluate {
            val ids = mutableListOf<String>()
            listOf("commonMainApi", "commonMainImplementation").forEach { cfg ->
                configurations.findByName(cfg)?.dependencies?.withType(ProjectDependency::class.java)?.forEach { dep ->
                    val other = rootProject.findProject(dep.path) ?: return@forEach
                    evaluationDependsOn(other.path)
                    if (other.pluginManager.hasPlugin("tech.kloos.kompound.demos")) {
                        ids += other.extensions.getByType<KompoundDemosExtension>().moduleId.get()
                    }
                }
            }
            val dup = ids.groupingBy { it }.eachCount().filterValues { it > 1 }.keys
            check(dup.isEmpty()) { "Duplicate Kompound moduleId(s): $dup. Set kompoundDemos { moduleId.set(...) }." }
            task.configure { moduleIds.set(ids.sorted()) }
        }
    }
}

public abstract class GenerateAllDemosTask : DefaultTask() {
    @get:Input public abstract val moduleIds: ListProperty<String>
    @get:Input public abstract val externalRegistries: ListProperty<String>
    @get:OutputDirectory public abstract val outputDirectory: DirectoryProperty

    @TaskAction
    public fun generate() {
        val refs = moduleIds.get().map { "$REGISTRY_PACKAGE.${registryClassName(it)}" } + externalRegistries.get().sorted()
        val dir = outputDirectory.get().asFile.resolve("tech/kloos/kompound/catalog").also { it.mkdirs() }
        val body = if (refs.isEmpty()) "emptyList()" else refs.joinToString(",\n        ", "listOf(\n        ", ",\n    )")
        dir.resolve("KompoundAllDemos.kt").writeText(
            """
            |package tech.kloos.kompound.catalog
            |
            |import tech.kloos.kompound.demo.DemoEntry
            |import tech.kloos.kompound.demo.DemoRegistry
            |
            |/** Generated by tech.kloos.kompound.catalog. Do not edit. */
            |public object KompoundAllDemos {
            |    public val registries: List<DemoRegistry> = $body
            |
            |    public val entries: List<DemoEntry> = registries
            |        .flatMap { it.entries }
            |        .also { all ->
            |            val dup = all.groupBy { it.qualifiedId }.filterValues { it.size > 1 }.keys
            |            check(dup.isEmpty()) { "Duplicate demo ids: ${'$'}dup" }
            |        }
            |        .sortedWith(compareBy({ it.moduleId }, { it.meta.id }))
            |}
            |""".trimMargin(),
        )
    }
}
