#!/usr/bin/env bash
# Writes maestro/flows/components/<category>/<demo>/50-fuzz.yaml for every demo (tag: fuzz, excluded from normal runs).
#
#   gen-fuzz-flows.sh [--seeds 8] [--base 1000]
#
# Each seed is one environment drawn from a seeded random generator: dark or light, LTR or RTL, font scale, density, and a theme that is either
# derived (random hue, saturation, corner radius: a plausible brand) or chaos (every colour role and radius random, see ChaosTheme). The flow opens the demo
# in it, checks that nothing crashed and takes a screenshot (`..._fuzz<seed>.png`) for maestro/visual/analyze.py. The same --base gives the same
# environments, so a failure is reproducible from the name of its screenshot.
set -eu
cd "$(dirname "$0")/../.."
SEEDS=8; BASE=1000
while [ $# -gt 0 ]; do case "$1" in --seeds) SEEDS="$2"; shift 2 ;; --base) BASE="$2"; shift 2 ;; *) echo "unknown option $1" >&2; exit 2 ;; esac; done

maestro/scripts/demo-ids.sh | while read -r id category; do
  dir="maestro/flows/components/$category/$id"
  [ -d "$dir" ] || { echo "no flow folder for $id" >&2; continue; }
  python3 - "$id" "$category" "$SEEDS" "$BASE" > "$dir/50-fuzz.yaml" <<'PY'
import random, sys
demo, category, seeds, base = sys.argv[1], sys.argv[2], int(sys.argv[3]), int(sys.argv[4])
print("# generated by maestro/scripts/gen-fuzz-flows.sh, do not edit")
print("appId: tech.kloos.kompound.catalog.maestro")
print(f"name: {demo} fuzz")
print("tags:\n  - fuzz\n  - slow")
print(f"  - component:{demo}\n  - category:{category}")
print(f"properties:\n  junitClassname: {demo}\n---")
for n in range(base, base + seeds):
    r = random.Random(n)
    dark = r.random() < 0.5
    rtl = r.random() < 0.25
    font = r.choice(["1.0", "1.0", "1.3", "2.0"])
    density = r.choice(["compact", "comfortable", "spacious"])
    if r.random() < 0.5:
        theme = f"chaos={n}"
    else:
        theme = f"hue={r.randrange(360)}&saturation={r.choice([0.0, 0.2, 0.55, 0.9, 1.0])}&roundness={r.choice([0, 0.5, 1, 1.5, 2])}"
    t, d = ("dark" if dark else "light"), ("rtl" if rtl else "ltr")
    print(f"# seed {n}: {t} {d} font {font} {density} {theme}")
    print("- runFlow:\n    file: ../../../_lib/open-demo.yaml")
    print(f"    env: {{ DEMO: {demo}, THEME: {t}, RTL: \"{str(rtl).lower()}\", FONT: \"{font}\", DENSITY: {density}, CONTROLS: \"{theme}\" }}")
    print("- runFlow: ../../../_lib/assert-no-crash.yaml")
    print("- runFlow:\n    file: ../../../_lib/shot.yaml")
    print(f"    env: {{ DEMO: {demo}, THEME: {t}, DIR: {d}, FONT: \"{font}\", DENSITY: {density}, LANG: en, FUZZ: _fuzz{n} }}")
PY
done
echo "wrote $(ls maestro/flows/components/*/*/50-fuzz.yaml | wc -l | tr -d ' ') flows"
