#!/usr/bin/env bash
# Writes maestro/flows/components/<category>/<demo>/40-visual.yaml for every demo (tag: visual, excluded from normal runs).
# One screenshot per environment of the matrix below; the files are generated, edit this script and run it again.
#
#   gen-visual-flows.sh
set -eu
cd "$(dirname "$0")/../.."
# theme dir font density lang
MATRIX=(
  "light ltr 1.0 comfortable en"
  "dark ltr 1.0 comfortable en"
  "light rtl 1.0 comfortable en"
  "light ltr 2.0 comfortable en"
  "light ltr 1.0 compact en"
)
maestro/scripts/demo-ids.sh | while read -r id category; do
  dir="maestro/flows/components/$category/$id"
  [ -d "$dir" ] || { echo "no flow folder for $id" >&2; continue; }
  {
    echo "# generated by maestro/scripts/gen-visual-flows.sh, do not edit"
    echo "appId: tech.kloos.kompound.catalog.maestro"
    echo "name: $id visual"
    echo "tags:"
    echo "  - visual"
    echo "  - slow"
    echo "  - component:$id"
    echo "  - category:$category"
    echo "properties:"
    echo "  junitClassname: $id"
    echo "---"
    for row in "${MATRIX[@]}"; do
      read -r theme d font density lang <<< "$row"
      rtl=false; [ "$d" = rtl ] && rtl=true
      echo "- runFlow:"
      echo "    file: ../../../_lib/open-demo.yaml"
      echo "    env: { DEMO: $id, THEME: $theme, RTL: \"$rtl\", FONT: \"$font\", DENSITY: $density, LANG: $lang }"
      echo "- runFlow:"
      echo "    file: ../../../_lib/shot.yaml"
      echo "    env: { DEMO: $id, THEME: $theme, DIR: $d, FONT: \"$font\", DENSITY: $density, LANG: $lang }"
    done
  } > "$dir/40-visual.yaml"
done
echo "wrote $(ls maestro/flows/components/*/*/40-visual.yaml | wc -l | tr -d ' ') flows"
