#!/usr/bin/env python3
"""Generates maestro/flows/_lib/strings.js from KompoundStrings.kt: every label of the library in en, de, fr, es and it.
Run it after changing KompoundStrings (coverage of the labels used by flows is checked by the flows themselves)."""
import re, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
src = (root / "kompound/src/commonMain/kotlin/tech/kloos/kompound/i18n/KompoundStrings.kt").read_text()
head = src[src.index("data class KompoundStrings("):src.index("companion object")]
defaults = dict(re.findall(r'val (\w+): String = "((?:[^"\\]|\\.)*)"', head))
langs = {"en": "English", "de": "German", "fr": "French", "es": "Spanish", "it": "Italian"}
out = {}
for code, name in langs.items():
    if code == "en":
        out[code] = dict(defaults); continue
    i = src.index(f"val {name}: KompoundStrings = KompoundStrings(")
    j = src.index("\n        )", i)
    block = src[i:j]
    d = dict(defaults)
    d.update(dict(re.findall(r'(\w+) = "((?:[^"\\]|\\.)*)"', block)))
    out[code] = d
lines = [
    "// GENERATED by maestro/scripts/gen-strings.py from KompoundStrings.kt: do not edit.",
    "// Kompound's own labels per language: the harness forces the language with the lang= parameter, so flows look for the words of that language.",
    "// Use: - runScript: { file: ../../../_lib/strings.js, env: { LANG: ${LANG} } }   then  ${output.s.showPassword}",
    "var S = {",
]
for code, d in out.items():
    items = ", ".join(f"{k}: '{v.replace(chr(39), chr(92) + chr(39))}'" for k, v in d.items())
    lines.append(f"  {code}: {{ {items} }}{',' if code != 'it' else ''}")
lines += ["};", "var lang = (typeof LANG !== 'undefined' && LANG) ? LANG : 'en';", "output.s = S[lang] || S.en;", ""]
(root / "maestro/flows/_lib/strings.js").write_text("\n".join(lines))
print(f"{len(defaults)} labels x {len(langs)} languages")
